apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promptshield.fullname" . }}
  labels:
    {{- include "promptshield.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "promptshield.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promptshield.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "promptshield.serviceAccountName" . }}
      containers:
        - name: enforcer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PS_ENFORCER_MODE
              value: {{ .Values.mode | quote }}
            {{- if .Values.database.useIAM }}
            - name: PS_DB_IAM_USER
              value: {{ .Values.database.iamUser | quote }}
            - name: AURORA_REGION
              value: {{ .Values.database.region | quote }}
            - name: AURORA_DB_NAME
              value: {{ .Values.database.dbName | quote }}
            - name: AURORA_PROXY_ENDPOINT
              value: {{ .Values.database.proxyEndpoint | quote }}
            - name: PS_PG_DSN
              value: {{ printf "postgres://@%s:5432/%s?sslmode=require" .Values.database.proxyEndpoint .Values.database.dbName | quote }}
            {{- end }}
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9091
              name: grpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
