receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s

exporters:
  logging:
    loglevel: info
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/jaeger, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
