package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

var supported = []string{"1.26", "1.27", "1.28"}

func main() {
	version := flag.String("version", "1.27", "Envoy major.minor version (e.g. 1.27)")
	mode := flag.String("mode", "ext_proc", "stub type: ext_proc | ext_authz")
	flag.Parse()

	if !isSupported(*version) {
		fmt.Fprintf(os.Stderr, "unsupported version %s (supported: %s)\n", *version, strings.Join(supported, ", "))
		os.Exit(1)
	}

	switch *mode {
	case "ext_proc":
		printExtProc(*version)
	case "ext_authz":
		printExtAuthz(*version)
	default:
		fmt.Fprintf(os.Stderr, "unknown mode %s\n", *mode)
		os.Exit(1)
	}
}

func isSupported(v string) bool {
	for _, s := range supported {
		if s == v {
			return true
		}
	}
	return false
}

func printExtProc(v string) {
	fmt.Printf(`# Envoy %s ext_proc stub generated by envoystub
static_resources:
  listeners:
  - name: inbound
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: backend }
          http_filters:
          - name: envoy.filters.http.ext_proc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProc
              grpc_service:
                google_grpc:
                  target_uri: ps-enforcer:9091
                  stat_prefix: ext_proc
              failure_mode_allow: true
          - name: envoy.filters.http.router
  clusters:
  - name: backend
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: backend, port_value: 8081 }
`, v)
}

func printExtAuthz(v string) {
	fmt.Printf(`# Envoy %s ext_authz stub generated by envoystub
static_resources:
  listeners:
  - name: inbound
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: backend }
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              http_service:
                server_uri:
                  uri: http://ps-enforcer:9090
                  cluster: ps-enforcer
                  timeout: 0.5s
                authorization_request:
                  allowed_headers:
                    patterns:
                      - exact: "content-type"
              failure_mode_allow: true
          - name: envoy.filters.http.router
  clusters:
  - name: backend
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: backend, port_value: 8081 }
  - name: ps-enforcer
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: ps-enforcer
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: ps-enforcer, port_value: 9090 }
`, v)
}
